# Generated by Django 5.2 on 2025-04-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("leftTeamScore", models.IntegerField(blank=True, null=True)),
                ("rightTeamScore", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
