# Generated by Django 5.2.4 on 2025-07-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Map",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("map", models.CharField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name="match",
            name="right_team",
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name="match",
            name="scheduled_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
