# Generated by Django 5.2.4 on 2025-08-05 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_map_match_right_team_match_scheduled_time"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Map",
        ),
    ]
