# Generated by Django 5.2.4 on 2025-09-16 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_map"),
    ]

    operations = [
        migrations.AddField(
            model_name="map",
            name="match",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.match",
            ),
        ),
        migrations.AddField(
            model_name="map",
            name="mode",
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name="match",
            name="left_team",
            field=models.CharField(blank=True),
        ),
    ]
